package com.jaga.swing.chart.example;

import com.jhw.swing.material.components.button.MaterialButtonsFactory;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.jhw.swing.ui.MaterialLookAndFeel;
import javax.swing.JButton;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class CHART_EXAMPLE extends javax.swing.JFrame {

    public CHART_EXAMPLE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    private void initComponents() {

        _PanelTransparent1 = new com.jhw.swing.material.components.container.panel._PanelTransparent();
        _MaterialButton1 = MaterialButtonsFactory.buildButton();
        _MaterialButton2 = MaterialButtonsFactory.buildButton();
        _MaterialButton3 = MaterialButtonsFactory.buildButton();
        _MaterialButton4 = MaterialButtonsFactory.buildButton();
        _MaterialButton5 = MaterialButtonsFactory.buildButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout _PanelTransparent1Layout = new javax.swing.GroupLayout(_PanelTransparent1);
        _PanelTransparent1.setLayout(_PanelTransparent1Layout);
        _PanelTransparent1Layout.setHorizontalGroup(
                _PanelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        _PanelTransparent1Layout.setVerticalGroup(
                _PanelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 369, Short.MAX_VALUE)
        );

        _MaterialButton1.setText("Bar");
        _MaterialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton1ActionPerformed(evt);
            }
        });

        _MaterialButton2.setText("PIE HOLLOW");
        _MaterialButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton2ActionPerformed(evt);
            }
        });

        _MaterialButton3.setText("PIE NORMAL");
        _MaterialButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton3ActionPerformed(evt);
            }
        });

        _MaterialButton4.setText("DOUBLE");
        _MaterialButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton4ActionPerformed(evt);
            }
        });

        _MaterialButton5.setText("LINE");
        _MaterialButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_PanelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(_MaterialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_MaterialButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_MaterialButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_MaterialButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_MaterialButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(_PanelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_MaterialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_MaterialButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_MaterialButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_MaterialButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_MaterialButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>                        

    private void _MaterialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton1ActionPerformed
        putChart(new BAR_EXAMPLE());
    }//GEN-LAST:event__MaterialButton1ActionPerformed

    private void _MaterialButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton2ActionPerformed
        putChart(new PIE_HOLLOW_EXAMPLE());
    }//GEN-LAST:event__MaterialButton2ActionPerformed

    private void _MaterialButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton3ActionPerformed
        putChart(new PIE_NORMAL_EXAMPLE());
    }//GEN-LAST:event__MaterialButton3ActionPerformed

    private void _MaterialButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton4ActionPerformed
        putChart(new CONVERT_EXAMPLE());
    }//GEN-LAST:event__MaterialButton4ActionPerformed

    private void _MaterialButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton5ActionPerformed
        putChart(new LINE_EXAMPLE());
    }//GEN-LAST:event__MaterialButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new MaterialLookAndFeel());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHART_EXAMPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//:variables
    private JButton _MaterialButton1;
    private JButton _MaterialButton2;
    private JButton _MaterialButton3;
    private JButton _MaterialButton4;
    private JButton _MaterialButton5;
    private JPanel _PanelTransparent1;
    // End of variables declaration                   

    private void putChart(JPanel panel) {
        this._PanelTransparent1.removeAll();
        this._PanelTransparent1.setLayout(new GridLayout(1, 1));
        this._PanelTransparent1.add(panel);
        this._PanelTransparent1.validate();
    }
}
